services:
  db:
    image: mongo:latest
    hostname: localhost
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/var/lib/mongo/data

volumes:
  mongo_data:
